### ISSUE TITLE
Seems to desync alot whenever you open Graphics, sound or input options

### ISSUE THREAD

**Issue by CrankySupertoonArchive** [CoderTimZ/NetplayInputPlugin#1]

**Comment by theboy181** [comment]
I think its best if you adjust all your settings before you join/host a game. When the emulator is navigating settings it will stop emulation in most cases.

**Comment by CrankySupertoonArchive** [comment]
Im just asking for a fix since im trying to set up netplay for a guild. I am trying a eariler version and seem to have a little more sucess

**Comment by CrankySupertoonArchive** [comment]
This is also very important

**Comment by CrankySupertoonArchive** [comment]
This might be able to be fixed with the pause emulation check mark but i havent tested

**Comment by CoderTimZ** [comment]
Which emulator are you using, and which version of that emulator?

**Comment by CrankySupertoonArchive** [comment]
Project64.2.4.0-673-g4967242a

**Comment by CoderTimZ** [comment]
I recommend using Project64 2.3.2. I've experienced desyncs using later versions. I also recommend not touching the settings too much after the game has started.

**Comment by furtabs** [comment]
Close
