### ISSUE TITLE
Switch Player Slots

### ISSUE THREAD

**Issue by KodaichiZero** [CoderTimZ/NetplayInputPlugin#10]
Hi There,

I noticed an issue with the netplay plugin where the server host will always be stuck as player 1, no way to change the slot. There should be a way to designate player slots, whether in the plugin options or the netplay GUI.

Thanks

**Comment by furtabs** [comment]
Eh I can try to work on it. 
I developed an emulator called Project 64 Netplay and is a very requested feature

https://github.com/Project64Netplay/Project64-Netplay

The developer of this plugin CoderTim owns another project called http://namemc.com and he kinda let this go

**Comment by KodaichiZero** [comment]
Ok I see. I think i meant to post this feature request on your GitHub actually. I have a friend who can't host a game and we want him to be player 1, so this would fix that. Very appreciated if you manage to do it. I could potentially give it a shot myself, I can code.

**Comment by CoderTimZ** [comment]
This feature already exists but it's not documented. The command is `/map <local_slot> <netplay_slot> [<local_slot> <netplay_slot>] [...]`. So for example, `/map 1 2` will map your local input from player 1 to player 2.

**Comment by CrankySupertoon** [comment]
How about you stop working on NameMC and actually update this with Cheat and Save Syncing and a  GUI For that
