### ISSUE TITLE
Lag Logs

### ISSUE THREAD

**Issue by Airsola01** [CoderTimZ/NetplayInputPlugin#12]
Hello there! I'm Airsola™ from Mario Party Netplay and we have been keeping up with all the quality updates you've been doing to make AQZ better, but there is one thing that we would like to request. The ability to see who changes the buffer/lag and to what value is no longer a feature. This is very important when you're playing with others to ensure that players don't cheat by changing the buffer during timing-intensive moments without anyone knowing. Do you think you could implement this feature back into AQZ?

**Comment by CoderTimZ** [comment]
Alright I've changed this in v93 (https://github.com/CoderTimZ/NetplayInputPlugin/commit/113feb3395836ee383553a7f35ac1cc2598b51ce).

**Comment by Airsola01** [comment]
Thank you so much!
