### ISSUE TITLE
Black Screen / Controller Log Request

### ISSUE THREAD

**Issue by Airsola01** [CoderTimZ/NetplayInputPlugin#13]
Hello! It's Airsola™ from Mario Party Netplay again. We've been doing some testing with the latest AQZ v94 and we've spotted an issue where starting the game results in a black screen for all players (which you may or may not be aware of by now). If it helps, from what we've tested, it seems that graphics plugin is not related to the issue, nor is changing the buffer before starting. We also tried doing a session using both a forwarded port and a ny server link, but the issue was present both times. Hopefully this information can help narrow down where this issue might be coming from.

On a separate note, we were also wondering if you could make controller port changes be logged like when changing the lag, to prevent players from maliciously messing with the ports during gameplay.

Thanks in advance! And if you need any type of help testing out changes, you can stop by MPN at any time!

**Comment by CoderTimZ** [comment]
Does it happen every time? Which emulator are you using?

**Comment by Airsola01** [comment]
For testing, we used both our MPN build of PJ64 which runs off of ver 2.3.2, and also the AQZ build on the play64 site.
As far as the black screen issue, it does not happen every time. 

We believed it could be linked to autolag vs setting lag before starting, so we ran different tests. It seems like newyork server doesn't give any problems in either MPN or AQZ build from what I've tested recently. However, when using my port, there's been a few inconsistent results, where my port works with someone but not with someone else (on v74 the port works with both people). Also, that same person that couldn't start the game with me tried their port with someone else and they were able to boot the game. Additionally, in one of the tests with the AQZ build, I had someone join me as Anonymous and we started the game without setting the lag, and the game black screened, but right after, I had that same person change their name before we started and the game booted. The third time we did the exact same thing with the name and it did not work.

**Comment by CoderTimZ** [comment]
Let me know if the latest version (v97) helps at all.

**Comment by Airsola01** [comment]
Whatever you did, it certainly seems to have fixed the issue! Thank you!

I guess that just leaves the request for logging controller port changes, if possible.

**Comment by CoderTimZ** [comment]
Glad to hear the issue was fixed!
Also, I've added controller port logging in https://github.com/CoderTimZ/NetplayInputPlugin/commit/37e7362f38796d067bc316a4737edc88f47c361d (v98).

**Comment by Airsola01** [comment]
Bless 🙏
