### ISSUE TITLE
Golf mode

### ISSUE THREAD

**Issue by fancy247** [CoderTimZ/NetplayInputPlugin#14]
Me and and a few others have started a recent Mario Golf 64 netplay community. We have resorted to using dolphin netplay with their version of golf mode for the players with better computers. But there is a growing need for a pj64 golf mode that works well. We have yet to get aqz's golf mode to work without major issues. We can get into specifics but for the most part with same saves, same build, and all same plugins it descyncs constantly. And this has been with six or more people testing constantly. Hoping we can find a solution together.

**Comment by CoderTimZ** [comment]
Are you using Project64 2.4.0, and if so, is “Randomize SI/PI interrupts” unchecked?

![gqMKq6Xe](https://user-images.githubusercontent.com/5505891/91208305-dd591900-e6be-11ea-80e3-2ae4551be06e.png)

**Comment by fancy247** [comment]
We were using 2.4 let me test this out with someone available and see if it
makes the difference. If I'm correct aqz golf mode changed from a button
like L or Z to toggle it to it auto doing it somehow?

**Comment by CoderTimZ** [comment]
Yes, it now toggles if you press any button at all.

**Comment by fancy247** [comment]
If I click off the window and do other things with me PC it will interior
the golf mode of another player?

**Comment by CoderTimZ** [comment]
If you click off the window, it will not interfere.

**Comment by fancy247** [comment]
I appreciate you getting back to me this quickly btw. I may ask very
specific questions because I make guides for our build downloads. It might
be a min before I get a hold of somebody who has the time to test this out
with me. I did find that the setting you mentioned was not turned off and
I'm hoping that fixes it. Gotcha I'll make sure to put that in the guide.

**Comment by CoderTimZ** [comment]
By the way, here is a cheat code I developed that will fix the jagged grid in Mario Golf:

https://www.play64.com/mario-golf-grid-fix/

**Comment by fancy247** [comment]
Nice work man. I've been finishing up a modd that brings the gbc chars over
with stats balanced for the game. You should join up if you like the game.

https://discord.gg/kkND8QF

But I understand if your not interested.

**Comment by fancy247** [comment]
We are testing it now.

**Comment by fancy247** [comment]
I need to make sure all of these are correct to get golf mode to work
correctly yes?

Interupter in defualt settings is off
Frame rate limit is off
No one presses any buttons during another person's play
Saves are the same
Same ROM
Golf mode is on
Plugins are the same

Me and someone just tested it a bit with these and we desync'd a bunch.
Going to test it with another player in a little bit. I'll let you know if
we see an improvement.

**Comment by CoderTimZ** [comment]
Yes, if you do all of those things, there should be no desyncs. I just tested it and it worked fine for me. Are you using the latest version of the netplay plugin (v99)?

**Comment by fancy247** [comment]
Yes we are. We used to use .20 and .72 a little for some time. I remember
.72 being ok for a bit. Ping isn't too much of a factor here huh? When we
tested it the other player had 160 when we direct connected and when we
tried the new York server we both had 60ish ping.

**Comment by CoderTimZ** [comment]
Yes, the point of golf mode is to make the ping irrelevant.

To help me narrow down the cause of the desyncs, please have everyone use the debug version of the netplay plugin. This version of the plugin will generate a file called input.log that contains a log of all button presses. If and when a desync occurs, have everyone close the emulator and then send each of the input.log files to me so I can compare them. If the log files differ, that means the netplay plugin caused the desync. If the files are identical, that means the desync was caused by something else.

Debug Version: [netplay_input_plugin.zip](https://github.com/CoderTimZ/NetplayInputPlugin/files/5126244/netplay_input_plugin.zip)

**Comment by fancy247** [comment]
Will do thanks.

**Comment by fancy247** [comment]
Figured out the issue my controller was somehow still using the mouse as an
input. It's working perfectly with a different friend now. Curious why did
you change it from the L button for toggle to any button? The only issue
with this for golf is no one can taunt or compliment now


<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by CoderTimZ** [comment]
I know it’s been a really long time since you posted this, but I figured I’d let you know in the latest update (bbbd77f002626f9dff269131ea5ad1342e9e110e), I exclude the Mario Golf taunt buttons from toggling the active client in golf mode.
