### ISSUE TITLE
Hosts list can freeze plugin window

### ISSUE THREAD

**Issue by minionprocyk** [CoderTimZ/NetplayInputPlugin#18]
Hey. Thanks for creating this plugin, I love it! 

I noticed when I add new hosts to the known servers list, the window seems to get locked up ONLY if that host does not have a running AQZ server. Seems like in the ping_public_server_list method, if a server is not reachable the window becomes frozen. I think we need a socket timeout when you try to connect, but was hoping you can take a quick look at it. It's hard for me to debug since I'm on linux and this is a windows project.

**Comment by CoderTimZ** [comment]
Hmm, that’s odd. The public servers are pinged by a separate thread. I just tried to reproduce this issue myself but everything worked fine. The window never froze, and after three seconds a “Ping Error” message appeared next to the invalid server.

**Comment by minionprocyk** [comment]
huh. Yeah i just tried this again and it seems to work???? Then I thought it might be a wine bug, but it works there too. Maybe it was an error while changing the code and stuff. who knows, thanks for sanity checking though.

As far as i can tell this is resolved
