### ISSUE TITLE
Something is causing the game to start slower then usual

### ISSUE THREAD

**Issue by CrankySupertoonArchive** [CoderTimZ/NetplayInputPlugin#2]
It takes either for 1-3 tries before the game actual loads sucessfully

**Comment by CrankySupertoonArchive** [comment]
This is a really important issue

**Comment by CoderTimZ** [comment]
Does the game start slow, or does it not load at all? Are you referring to when you first load the game into the emulator, or when you use the `/start` command to actually start playing? Do you have autolag enabled or disabled? Are you using Project64 2.3.2 or a different emulator? Which version of the netplay plugin are you using?

**Comment by CrankySupertoonArchive** [comment]
Im using Project64 2.3.2, AQZ Netplay v60. im running /start and it just blackscreened. Autolag doesnt make a difference

**Comment by CrankySupertoonArchive** [comment]
Just because i havent responded doesn't make this invalid. It is a prone issue with any build

**Comment by CoderTimZ** [comment]
Unfortunately I have been unable to reproduce this issue. Could you list the exact steps you take prior to this issue occurring? Also, could you please answer the following questions:

When the issue occurs, does the "Starting game..." message still appear in the AQZ window? Are there any error messages? Is the AQZ window still responsive (can you still drag it around the screen and type in the text box)? Do chat messages still get sent and received? When you close the emulator, does the AQZ window disappear immediately or stay visible for a while?

**Comment by furtabs** [comment]
I have a similar issue when starting the game no error messages and the menu is still responsive. Chat does still get sent. When I close The AQZ window it starts fine. This is the build https://github.com/NailNatail64/MarioEverything-Project64Netplay?files=1

**Comment by furtabs** [comment]
![image](https://user-images.githubusercontent.com/48419040/54639628-3e110a80-4a64-11e9-9219-b17d83bd6f52.png)

**Comment by CoderTimZ** [comment]
@CindyLouWho03 Are you using the netplay plugin in combination with cheats?

**Comment by furtabs** [comment]
The issue is the HLE sound plugin

**Comment by furtabs** [comment]
Close
