### ISSUE TITLE
Dedicated Servers dont show on the Bar, command does work

### ISSUE THREAD

**Issue by CrankySupertoonArchive** [CoderTimZ/NetplayInputPlugin#3]
Care adding a status part of the website to see downtime on the decicated servers

**Comment by CoderTimZ** [comment]
The server seems fine to me right now.

**Comment by CrankySupertoonArchive** [comment]
![image](https://user-images.githubusercontent.com/26016256/50565005-60627a00-0cf8-11e9-8ad0-0c3177a2d02b.png)

**Comment by CoderTimZ** [comment]
How long have you been having this problem and what version of Windows are you using?

**Comment by CrankySupertoonArchive** [comment]
48-72 hours and Windows 10. It shows up every so often but never lets me join. Also my entire guild cannot see it so you might want to try to duplicate the bug

**Comment by CoderTimZ** [comment]
Does it work with the latest version of the netplay plugin? The server doesn't support version 46.

**Comment by CrankySupertoonArchive** [comment]
i have tried both

**Comment by CoderTimZ** [comment]
Are you able to manually join the server with the `/join new-york.play64.com` command with version 60 of the netplay plugin?

**Comment by CrankySupertoonArchive** [comment]
Oh wow i can it just doesnt show

**Comment by CoderTimZ** [comment]
I've changed how the public server list is loaded in the latest build (v68). Please let me know if the public server list loads for you with this version.

**Comment by furtabs** [comment]
Close
