### ISSUE TITLE
Will not show MouseInjector.dll input plugin as an option for input.

### ISSUE THREAD

**Issue by WACOMalt** [CoderTimZ/NetplayInputPlugin#4]
Trying to use the MouseInjector plugin from 1964 but using aqz netplay in either 1964 or trying both in PJ64 neither shows MouseInjector as a valid option from inside of AQZ NEtplay's options.

**Comment by CoderTimZ** [comment]
Unfortunately the MouseInjector plugin is only supported by @carnivoroussociety’s fork of 1964.<sup>1</sup>

<sup>1</sup>https://github.com/carnivoroussociety/MouseInjector/blob/431da04fd02b078afd50304c74c67e55e785eb51/maindll.c#L840 

> no emulator supports this other than my disgusting version of 1964 (awful hack that i created because plugins are not complicated enough and i don't know what the f**k i am doing as evident from the code i've written)
