### ISSUE TITLE
Mario Kart 64

### ISSUE THREAD

**Issue by ErinNyx** [CoderTimZ/NetplayInputPlugin#6]
So I can play with 2 players no problem, but as soon as we added a third person we couldn't start the emulation - we're all stuck on a black screen. The emulation shouldn't be paused as we all have the setting for emulations being paused while tabbed out of the game is disabled.

**Comment by furtabs** [comment]
This is what I use https://pj64netplay-emu.ml/

**Comment by CoderTimZ** [comment]
I recently discovered if you try to configure your controller settings after you’ve opened the ROM but before you run the `/start` command, Project64 2.4.0 will freeze on a black screen. This problem no longer occurs with Project64 3.0.1 (available now at https://www.play64.com/netplay-plugin/). With version 3.0.1, the emulator will pause in this situation, but you can simply unpause it to get past the black screen.

**Comment by CoderTimZ** [comment]
I _think_ I’ve completely fixed the black screen issue in the latest update (https://github.com/CoderTimZ/project64/commit/475fa5819e386f3346b5c4d9361329fcd545aa56) of my custom fork of Project64 3.0.1, now available at www.play64.com.
