### ISSUE TITLE
How to create own Server

### ISSUE THREAD

**Issue by Chlitzxer** [CoderTimZ/NetplayInputPlugin#7]
Hi first to thank you for doing this is amazing!

I was using Hamachi for a while and is not very stable anymore, I discovered using new-york.play64.com and works great, my question actually is how I can create my own server on my VPS or dedicated server most of my old friends live in countries that are far from me and I would like to get servers closer to them, not sure if this is possible but that would be amazing.

Thanks in advance!

**Comment by CoderTimZ** [comment]
1. Install `git`, `make`, and `g++` on your server if they are not already installed.

2. Clone the repository and build the project with the following commands:

```
git clone --recursive https://github.com/CoderTimZ/NetplayInputPlugin.git
cd ./NetplayInputPlugin/NetplayInputPlugin/
make
```

3. Run the server with:

```
./netplay_server
```

**Comment by Chlitzxer** [comment]
> 1. Install `git`, `make`, and `g++` on your server if they are not already installed.
> 2. Clone the repository and build the project with the following commands:
> 
> ```
> git clone --recursive https://github.com/CoderTimZ/NetplayInputPlugin.git
> cd ./NetplayInputPlugin/NetplayInputPlugin/
> make
> ```
> 
> 1. Run the server with:
> 
> ```
> ./netplay_server
> ```

Excellent! What OS you do recommend for the installation? And what ports should I open to avoid any conflicts, thanks in advance!

**Comment by CoderTimZ** [comment]
The `new-york.play64.com` server uses Ubuntu, but any Linux OS will probably work fine. The server and client use port 6400 by default.

**Comment by Chlitzxer** [comment]
@CoderTimZ I opened an issue that I have after using the make command :( https://github.com/CoderTimZ/NetplayInputPlugin/issues/29

My next question, is how to I create a DLL that shows only my host to share with my friends so they don't have to do anything else than just click on any of my servers?

**Comment by CoderTimZ** [comment]
You could hard-code your server addresses in the DLL, or you could replace the server list API URL (http://api.play64.com/servers.txt) in the DLL with your own server list that you host yourself.
