### ISSUE TITLE
Independence of any emulator

### ISSUE THREAD

**Issue by kaillerareborn** [CoderTimZ/NetplayInputPlugin#8]
Hey Tim.

Is there any chance to make this plugin independent of Project64 in order to implement it in any other emulator? Like Kaillera and their functions explained in its [SDK package](http://www.kaillera.com/files/kaillera-0.9-sdk.zip).

As of right now, the plugin has a basic GUI like Kaillera, but it lacks of a Master server list / Waiting games list. The way it works is that the servers pings to the main website every minute to update how many users are inside and the games that are being hosted.

![ar0](https://user-images.githubusercontent.com/55330831/64913718-63e24800-d745-11e9-9c86-d49a311ef773.PNG)

Users have a way to bookmark their favorite servers as well, along with a quit message that will appear every time they leave a server.

![aq1](https://user-images.githubusercontent.com/55330831/64913742-07cbf380-d746-11e9-822d-add61877ae10.PNG)

The master servers list shows the name of the servers, location, version used, etc. (servers are sorted by ping by default)

![aq2](https://user-images.githubusercontent.com/55330831/64913752-5f6a5f00-d746-11e9-9574-9fb89565672b.PNG)

Once in a server, there's the typical general chat, the list of users and the games that are being hosted by the users. Inside the game room, there are basic functions such as "Start" to start the game, "Drop" to stop the emulation & close the game, "Kick" to kick a player (only the game room owner can do this) and "Close" to leave the current game room.

AQZ could become big if these features were implemented.

Regards.

**Comment by furtabs** [comment]
You realise AQZ is the guys Internet name right?

**Comment by CoderTimZ** [comment]
I am familiar with Kaillera, but I have no plans to make AQZ compatible with it.

**Comment by kaillerareborn** [comment]
@CoderTimZ I didn't suggested to make it compatible with Kaillera in any way, sorry if I wasn't clear enough in the first message.

What I meant is to make it more Kaillera alike. Currently there's a Servers list and it counts with a basic chat feature, so the infrastructure is there in some way. Of course it's easier said than done and would require some serious changes, but it has a lot of potential in my opinion.

P.S. It's good to know that the plugin is still being improved. 👍🏻

**Comment by CoderTimZ** [comment]
Perhaps one day I will implement the features you’ve suggested, but right now this project is just a small hobby of mine.
